In [1]:
import numpy as np

### **Vectors**

In [2]:
x = np.array([1,2,3])
print(x)

[1 2 3]


### **Matrices**

In [3]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a.shape)

(2, 3)


In [4]:
a1 = np.array([[1,2,3],
               [3,2,1]])
b1 = np.array([[2,1],
               [1,3],
               [1,1]])
a1@b1

array([[ 7, 10],
       [ 9, 10]])

In [5]:
a2 = np.array([[1,2,3],
               [3,2,1],
               [4,2,2]])
a2_inv = np.linalg.pinv(a2)
print(a2_inv)

[[-0.25 -0.25  0.5 ]
 [ 0.25  1.25 -1.  ]
 [ 0.25 -0.75  0.5 ]]


In [6]:
a2[::2,:]

array([[1, 2, 3],
       [4, 2, 2]])

In [7]:
a2[[0,2],:]

array([[1, 2, 3],
       [4, 2, 2]])

In [8]:
a2[:2,:2]

array([[1, 2],
       [3, 2]])

In [9]:
a2[-2:,:2]

array([[3, 2],
       [4, 2]])

In [10]:
print(a2[2, -2:])
a2[2:3,-2:][0]

[2 2]


array([2, 2])